# Generated by Django 6.0.7 on 2026-08-22 13:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('official_email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number (10-15 digits).', regex='^\\+?[0-9]{10,15}$')])),
                ('designation', models.CharField(max_length=120)),
                ('employee_staff_id', models.CharField(blank=True, max_length=60)),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('University', 'University'), ('Deemed University', 'Deemed University'), ('Autonomous College', 'Autonomous College'), ('College', 'College'), ('Institute', 'Institute'), ('Polytechnic', 'Polytechnic'), ('ITI', 'ITI'), ('Other', 'Other')], max_length=30)),
                ('institution_website', models.URLField()),
                ('institution_email_domain', models.CharField(max_length=255)),
                ('institution_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit PIN Code.', regex='^[1-9][0-9]{5}$')])),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('placement_department_name', models.CharField(max_length=255)),
                ('placement_office_email', models.EmailField(max_length=254)),
                ('approximate_student_strength', models.PositiveIntegerField()),
                ('courses_offered', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['institution_name', 'full_name'],
            },
        ),
    ]
