# Generated by Django 6.0.7 on 2026-08-28 15:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0003_move_institution_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('candidate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('department_id', models.CharField(blank=True, max_length=120)),
                ('program', models.CharField(choices=[('B.Tech', 'B.Tech'), ('B.E.', 'B.E.'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('B.Com', 'B.Com'), ('B.Sc.', 'B.Sc.'), ('BA', 'BA'), ('BMS', 'BMS'), ('BBM', 'BBM'), ('B.Des', 'B.Des'), ('B.Arch', 'B.Arch'), ('B.Pharm', 'B.Pharm'), ('MBBS', 'MBBS'), ('BDS', 'BDS'), ('BAMS', 'BAMS'), ('BHMS', 'BHMS'), ('BPT', 'BPT'), ('B.Sc. Nursing', 'B.Sc. Nursing'), ('B.Ed', 'B.Ed'), ('LLB', 'LLB'), ('BA LLB', 'BA LLB'), ('BBA LLB', 'BBA LLB'), ('BJMC', 'BJMC'), ('BHM', 'BHM'), ('BFA', 'BFA'), ('B.Voc', 'B.Voc'), ('M.Tech', 'M.Tech'), ('M.E.', 'M.E.'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('PGDM', 'PGDM'), ('M.Com', 'M.Com'), ('M.Sc.', 'M.Sc.'), ('MA', 'MA'), ('M.Des', 'M.Des'), ('M.Arch', 'M.Arch'), ('M.Pharm', 'M.Pharm'), ('M.Ed', 'M.Ed'), ('LLM', 'LLM'), ('MPT', 'MPT'), ('Diploma', 'Diploma'), ('ITI', 'ITI'), ('PG Diploma', 'PG Diploma'), ('Ph.D.', 'Ph.D.'), ('Other', 'Other')], max_length=120)),
                ('specialization', models.CharField(blank=True, max_length=120)),
                ('batch_year', models.PositiveIntegerField()),
                ('current_year', models.PositiveIntegerField()),
                ('college_email', models.EmailField(max_length=254)),
                ('personal_email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number (10-15 digits).', regex='^\\+?[0-9]{10,15}$')])),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer Not to Say')], max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('placement_status', models.CharField(choices=[('not_started', 'Not Started'), ('applying', 'Applying'), ('shortlisted', 'Shortlisted'), ('placed', 'Placed')], default='not_started', max_length=30)),
                ('placement_eligible', models.BooleanField(default=True)),
                ('resume_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('internships', models.JSONField(blank=True, default=list)),
                ('work_experience', models.JSONField(blank=True, default=list)),
                ('preferred_roles', models.JSONField(blank=True, default=list)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('expected_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profiles', to='TalentBroIns.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profiles', to='TalentBroIns.userprofile')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
