# Generated by Django 6.0.7 on 2026-08-30 08:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0006_studentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='batch_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profiles', to='TalentBroIns.institution'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='college_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='current_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer Not to Say')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number (10-15 digits).', regex='^\\+?[0-9]{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='personal_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='program',
            field=models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('B.E.', 'B.E.'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('B.Com', 'B.Com'), ('B.Sc.', 'B.Sc.'), ('BA', 'BA'), ('BMS', 'BMS'), ('BBM', 'BBM'), ('B.Des', 'B.Des'), ('B.Arch', 'B.Arch'), ('B.Pharm', 'B.Pharm'), ('MBBS', 'MBBS'), ('BDS', 'BDS'), ('BAMS', 'BAMS'), ('BHMS', 'BHMS'), ('BPT', 'BPT'), ('B.Sc. Nursing', 'B.Sc. Nursing'), ('B.Ed', 'B.Ed'), ('LLB', 'LLB'), ('BA LLB', 'BA LLB'), ('BBA LLB', 'BBA LLB'), ('BJMC', 'BJMC'), ('BHM', 'BHM'), ('BFA', 'BFA'), ('B.Voc', 'B.Voc'), ('M.Tech', 'M.Tech'), ('M.E.', 'M.E.'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('PGDM', 'PGDM'), ('M.Com', 'M.Com'), ('M.Sc.', 'M.Sc.'), ('MA', 'MA'), ('M.Des', 'M.Des'), ('M.Arch', 'M.Arch'), ('M.Pharm', 'M.Pharm'), ('M.Ed', 'M.Ed'), ('LLM', 'LLM'), ('MPT', 'MPT'), ('Diploma', 'Diploma'), ('ITI', 'ITI'), ('PG Diploma', 'PG Diploma'), ('Ph.D.', 'Ph.D.'), ('Other', 'Other')], default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Legacy: the institution staff member who entered this candidate.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profiles', to='TalentBroIns.userprofile'),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
