# Generated by Django 6.0.7 on 2026-08-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0007_candidateprofile_college_name_candidateprofile_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewDimensionScore',
        ),
        migrations.DeleteModel(
            name='InterviewQuestion',
        ),
        migrations.DeleteModel(
            name='InterviewResponse',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]