# Generated by Django 6.0.7 on 2026-08-30 13:16

from django.db import migrations, models


def backfill_user_role(apps, schema_editor):
    """Seed user_role from the legacy derivation so existing accounts keep
    their effective role once the stored field takes over.

    Staff/superuser or Institution-linked accounts => institution_staff,
    everything else => student (matching the previous user_role()).
    """
    UserProfile = apps.get_model('TalentBroIns', 'UserProfile')
    ROLE_STUDENT = 'student'
    ROLE_INSTITUTION_STAFF = 'institution_staff'
    for profile in UserProfile.objects.all():
        user = profile.user
        if user.is_superuser or user.is_staff or hasattr(user, 'institution'):
            profile.user_role = ROLE_INSTITUTION_STAFF
        else:
            profile.user_role = ROLE_STUDENT
        profile.save(update_fields=['user_role'])


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0008_remove_interviewquestion_interview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('student', 'Student'), ('institution_staff', 'Institution Staff')], default='student', max_length=20),
        ),
        migrations.RunPython(backfill_user_role, migrations.RunPython.noop),
    ]
