# Generated by Django 6.0.7 on 2026-08-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0009_userprofile_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_role',
        ),
    ]
