# Generated by Django 6.0.7 on 2026-08-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0010_remove_userprofile_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='candidate_intent',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
