# Generated by Django 6.0.7 on 2026-08-30 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0012_mockinterview_mockinterviewmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='TalentBroIns.institution'),
        ),
    ]
