# Generated by Django 6.0.7 on 2026-08-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0013_userprofile_institution_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='departments',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
