# Generated by Django 6.0.7 on 2026-08-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0014_institution_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterviewmessage',
            name='panelist',
            field=models.CharField(blank=True, choices=[('atlas', 'Atlas (Integrity Monitor)'), ('maya', 'Maya (Communication & HR)'), ('albert', 'Albert (Technical Architect)'), ('peter', 'Peter (Management & Leadership)'), ('daniel', 'Daniel (Decision Science)'), ('ada', 'Ada (Analytical & Logical Thinking)'), ('carl', 'Carl (Behavioral Intelligence)')], default='', help_text='Which panel member produced this message (assistant messages only).', max_length=20),
        ),
    ]
