# Generated by Django 6.0.7 on 2026-08-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0015_mockinterviewmessage_panelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterview',
            name='duration',
            field=models.CharField(blank=True, default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='panelists',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
