# Generated by Django 6.0.7 on 2026-08-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0016_mockinterview_duration_mockinterview_panelists'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterviewmessage',
            name='tone',
            field=models.CharField(blank=True, default='', help_text="Detected engagement/tone of the candidate's answer (positive, neutral, negative).", max_length=10),
        ),
    ]
