# Generated by Django 6.0.7 on 2026-08-31 14:10

from django.db import migrations, models


def copy_department_id(apps, schema_editor):
    CandidateProfile = apps.get_model('TalentBroIns', 'CandidateProfile')
    for profile in CandidateProfile.objects.all().iterator():
        if profile.department_id:
            profile.department = profile.department_id
            profile.save(update_fields=['department'])


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0017_mockinterviewmessage_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(copy_department_id, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='department_id',
        ),
    ]
