# Generated by Django 6.0.7 on 2026-08-31 14:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0018_remove_candidateprofile_college_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='ClientProfile',
        ),
    ]
