# Generated by Django 6.0.7 on 2026-08-31 14:52

from django.db import migrations, models


def merge_last_name(apps, schema_editor):
    CandidateProfile = apps.get_model('TalentBroIns', 'CandidateProfile')
    for profile in CandidateProfile.objects.all().iterator():
        if profile.first_name or profile.last_name:
            combined = f'{profile.first_name} {profile.last_name}'.strip()
            if combined:
                profile.first_name = combined
            if profile.last_name:
                profile.save(update_fields=['first_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0019_clientprofile_alter_candidateprofile_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(merge_last_name, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='last_name',
        ),
    ]