# Generated by Django 6.0.7 on 2026-08-31 14:59

from django.db import migrations, models


def copy_first_name(apps, schema_editor):
    CandidateProfile = apps.get_model('TalentBroIns', 'CandidateProfile')
    for profile in CandidateProfile.objects.all().iterator():
        if profile.first_name and not profile.full_name:
            profile.full_name = profile.first_name
            profile.save(update_fields=['full_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0020_alter_candidateprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'ordering': ['full_name']},
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(copy_first_name, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='student',
        ),
    ]