# Generated by Django 6.0.7 on 2026-08-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0021_alter_candidateprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='access',
            field=models.CharField(choices=[('beta', 'Beta'), ('master', 'Master')], default='beta', max_length=20),
        ),
    ]
