# Generated by Django 6.0.7 on 2026-09-01 16:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0023_candidateprofile_required_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profiles', to='TalentBroIns.institution'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number (10-15 digits).', regex='^\\+?[0-9]{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='employee_staff_id',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number (10-15 digits).', regex='^\\+?[0-9]{10,15}$')]),
        ),
    ]
