# Generated by Django 6.0.7 on 2026-09-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0024_alter_candidateprofile_cgpa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='resume_url',
        ),
    ]
