# Generated by Django 6.0.7 on 2026-09-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0025_remove_candidateprofile_resume_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='avatar',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='avatar',
            field=models.URLField(blank=True, default=''),
        ),
    ]
