# Generated by Django 6.0.7 on 2026-09-08 05:00

from django.db import migrations, models

# Profiles that already had every required placement field filled in were
# completed under the (previously client-side enforced) ID-verification gate,
# so they are treated as verified going forward. This keeps the newly-compulsory
# id_verification step from locking out existing, already-complete students.
def backfill_verified(apps, schema_editor):
    CandidateProfile = apps.get_model('TalentBroIns', 'CandidateProfile')
    candidates = CandidateProfile.objects.exclude(
        college__isnull=True,
    ).exclude(
        department='',
    ).exclude(
        program='',
    ).exclude(
        start_year__isnull=True,
    ).exclude(
        end_year__isnull=True,
    ).exclude(
        mobile_number='',
    ).exclude(
        date_of_birth__isnull=True,
    ).exclude(
        gender='',
    ).exclude(
        cgpa__isnull=True,
    ).exclude(
        linkedin_url='',
    )
    candidates.update(id_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0029_institution_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_verified, migrations.RunPython.noop),
    ]