# Generated by Django 6.0.7 on 2026-09-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0030_add_candidateprofile_id_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.URLField(blank=True, default=''),
        ),
    ]
