# Generated by Django 6.0.7 on 2026-09-09 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0031_institution_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='candidate_intent',
        ),
    ]
