# Generated by Django 6.0.7 on 2026-09-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0032_remove_candidateprofile_candidate_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterview',
            name='panelist_response',
            field=models.JSONField(blank=True, default=dict, help_text='Per-panelist feedback after the interview completes. Keys are panelist IDs, values are their feedback text.'),
        ),
    ]
