# Generated by Django 6.0.7 on 2026-09-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0033_add_panelist_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterview',
            name='suspection',
            field=models.IntegerField(default=0, help_text='Number of times the candidate looked away from the screen during the interview.'),
        ),
    ]
