# Generated by Django 6.0.7 on 2026-09-13 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0034_add_suspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('clarity', models.PositiveSmallIntegerField(default=0, help_text='Clarity score (0–100).')),
                ('fluency', models.PositiveSmallIntegerField(default=0, help_text='Fluency score (0–100).')),
                ('grammar', models.PositiveSmallIntegerField(default=0, help_text='Grammar score (0–100).')),
                ('vocabulary', models.PositiveSmallIntegerField(default=0, help_text='Vocabulary score (0–100).')),
                ('pronunciation', models.PositiveSmallIntegerField(default=0, help_text='Pronunciation score (0–100).')),
                ('confidence', models.PositiveSmallIntegerField(default=0, help_text='Confidence score (0–100).')),
                ('answer_structure', models.PositiveSmallIntegerField(default=0, help_text='Answer Structure score (0–100).')),
                ('relevance', models.PositiveSmallIntegerField(default=0, help_text='Relevance score (0–100).')),
                ('speaking_rate', models.PositiveSmallIntegerField(default=0, help_text='Speaking Rate score (0–100).')),
                ('pause_frequency', models.PositiveSmallIntegerField(default=0, help_text='Pause Frequency score (0–100).')),
                ('average_pause_duration', models.FloatField(default=0.0, help_text='Average pause duration in seconds.')),
                ('filler_words', models.PositiveIntegerField(default=0, help_text='Count of filler words (uh, um, like, you know...).')),
                ('repeated_words', models.PositiveIntegerField(default=0, help_text='Count of repeated words/phrases.')),
                ('sentence_restarts', models.PositiveIntegerField(default=0, help_text='Count of sentence restarts.')),
                ('intonation', models.PositiveSmallIntegerField(default=0, help_text='Intonation score (0–100).')),
                ('speech_rhythm', models.PositiveSmallIntegerField(default=0, help_text='Speech Rhythm score (0–100).')),
                ('voice_modulation', models.PositiveSmallIntegerField(default=0, help_text='Voice Modulation score (0–100).')),
                ('listening_skills', models.PositiveSmallIntegerField(default=0, help_text='Listening Skills score (0–100).')),
                ('response_quality', models.PositiveSmallIntegerField(default=0, help_text='Response Quality score (0–100).')),
                ('professional_tone', models.PositiveSmallIntegerField(default=0, help_text='Professional Tone score (0–100).')),
                ('conversational_skills', models.PositiveSmallIntegerField(default=0, help_text='Conversational Skills score (0–100).')),
                ('vocabulary_diversity', models.PositiveSmallIntegerField(default=0, help_text='Vocabulary Diversity score (0–100).')),
                ('grammar_error_count', models.PositiveIntegerField(default=0, help_text='Number of grammar errors detected (0–100).')),
                ('pronunciation_accuracy', models.PositiveSmallIntegerField(default=0, help_text='Pronunciation Accuracy score (0–100).')),
                ('communication_score', models.PositiveSmallIntegerField(default=0, help_text='Overall Communication Score (0–100).')),
                ('workplace_communication_readiness', models.PositiveSmallIntegerField(default=0, help_text='Workplace Communication Readiness score (0–100).')),
                ('interview_readiness', models.PositiveSmallIntegerField(default=0, help_text='Interview Readiness score (0–100).')),
                ('improvement_rate', models.PositiveSmallIntegerField(default=0, help_text='Improvement Rate (0–100 or %).')),
                ('recurring_mistakes', models.TextField(blank=True, default='')),
                ('strengths', models.TextField(blank=True, default='')),
                ('areas_for_improvement', models.TextField(blank=True, default='')),
                ('ai_recommendations', models.TextField(blank=True, default='')),
                ('practice_priorities', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
