# Generated by Django 6.0.7 on 2026-09-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0035_add_communication_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationtraining',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='When the session ended and the transcript was locked so the analysis could be generated.', null=True),
        ),
        migrations.AddField(
            model_name='communicationtraining',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
