# Generated by Django 6.0.7 on 2026-09-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0037_add_aplr_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplrtraining',
            name='category',
            field=models.CharField(choices=[('quantitative', 'Quantitative Aptitude'), ('logical_reasoning', 'Logical Reasoning'), ('verbal', 'Verbal Reasoning'), ('data_interpretation', 'Data Interpretation'), ('puzzle', 'Puzzles'), ('miscellaneous', 'Miscellaneous')], default='puzzle', max_length=40),
        ),
    ]
