# Generated by Django 6.0.7

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0038_alter_aplrtraining_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicMathTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('addition_subtraction', 'Addition & Subtraction'), ('multiplication_division', 'Multiplication & Division'), ('fractions_decimals', 'Fractions & Decimals'), ('percentage', 'Percentages'), ('ratio_average', 'Ratio & Average'), ('mental_math', 'Mental Math')], default='mental_math', max_length=40)),
                ('question', models.TextField(blank=True, default='')),
                ('answer', models.TextField(blank=True, default='')),
                ('solution', models.TextField(blank=True, default='')),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('solved', 'Solved'), ('gave_up', 'Gave Up')], default='active', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of tries the student made before resolving the question.')),
                ('hints_used', models.PositiveIntegerField(default=0, help_text='Number of hints Albert handed out during the attempt.')),
                ('points_awarded', models.PositiveIntegerField(default=0, help_text='XP earned for solving this question (0 when given up).')),
                ('star_rating', models.PositiveSmallIntegerField(default=0, help_text='Accuracy/speed quality shown by the student (1–5) when solved.')),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_math_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'basic_math',
                'ordering': ['-created_at'],
            },
        ),
    ]