# Generated by Django 6.0.7 on 2026-09-14 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0039_add_basic_math_training'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('clarity', models.PositiveSmallIntegerField(default=0, help_text='Clarity score (0–100).')),
                ('fluency', models.PositiveSmallIntegerField(default=0, help_text='Fluency score (0–100).')),
                ('grammar', models.PositiveSmallIntegerField(default=0, help_text='Grammar score (0–100).')),
                ('vocabulary', models.PositiveSmallIntegerField(default=0, help_text='Vocabulary score (0–100).')),
                ('pronunciation', models.PositiveSmallIntegerField(default=0, help_text='Pronunciation score (0–100).')),
                ('confidence', models.PositiveSmallIntegerField(default=0, help_text='Confidence score (0–100).')),
                ('intonation', models.PositiveSmallIntegerField(default=0, help_text='Intonation score (0–100).')),
                ('professional_tone', models.PositiveSmallIntegerField(default=0, help_text='Professional Tone score (0–100).')),
                ('speaking_score', models.PositiveSmallIntegerField(default=0, help_text='Overall English speaking score (0–100).')),
                ('recurring_mistakes', models.TextField(blank=True, default='')),
                ('strengths', models.TextField(blank=True, default='')),
                ('areas_for_improvement', models.TextField(blank=True, default='')),
                ('ai_recommendations', models.TextField(blank=True, default='')),
                ('practice_count', models.PositiveIntegerField(default=0, help_text='Number of practice rounds finished (recomputed on each finalize).')),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='One English training record per user.', on_delete=django.db.models.deletion.CASCADE, related_name='english_training', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'english_training',
            },
        ),
    ]
