# Generated by Django 6.0.7 on 2026-09-14 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0040_englishtraining'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SituationalProblemSolvingTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('workplace_conflict', 'Workplace Conflict'), ('leadership_dilemma', 'Leadership Dilemma'), ('team_management', 'Team Management'), ('decision_making', 'Decision Making'), ('ethical_dilemma', 'Ethical Dilemma'), ('crisis_management', 'Crisis Management')], default='decision_making', max_length=40)),
                ('question', models.TextField(blank=True, default='')),
                ('answer', models.TextField(blank=True, default='')),
                ('solution', models.TextField(blank=True, default='')),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('solved', 'Solved'), ('gave_up', 'Gave Up')], default='active', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of tries the student made before resolving the scenario.')),
                ('hints_used', models.PositiveIntegerField(default=0, help_text='Number of hints Peter handed out during the attempt.')),
                ('points_awarded', models.PositiveIntegerField(default=0, help_text='XP earned for solving this scenario (0 when given up).')),
                ('star_rating', models.PositiveSmallIntegerField(default=0, help_text='Management judgement quality shown by the student (1–5) when solved.')),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situational_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'situational_training',
                'ordering': ['-created_at'],
            },
        ),
    ]
