# Generated by Django 6.0.7 on 2026-09-14 - remove the Data Structures technical category.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0042_technicaltraining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicaltraining',
            name='category',
            field=models.CharField(choices=[('basics', 'Basics & Logic'), ('arrays_strings', 'Arrays & Strings'), ('searching_sorting', 'Searching & Sorting'), ('recursion', 'Recursion'), ('algorithms', 'Algorithms & Complexity'), ('debugging', 'Debugging')], default='basics', max_length=40),
        ),
    ]