# Generated by Django 6.0.7 on 2026-09-14 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0043_alter_technicaltraining_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DSATraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('arrays_strings', 'Arrays & Strings'), ('linked_lists', 'Linked Lists'), ('stacks_queues', 'Stacks & Queues'), ('hash_maps', 'Hash Maps & Sets'), ('trees', 'Trees'), ('graphs', 'Graphs'), ('searching_sorting', 'Searching & Sorting'), ('dynamic_programming', 'Dynamic Programming')], default='arrays_strings', max_length=40)),
                ('question', models.TextField(blank=True, default='')),
                ('answer', models.TextField(blank=True, default='')),
                ('solution', models.TextField(blank=True, default='')),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('solved', 'Solved'), ('gave_up', 'Gave Up')], default='active', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of tries the student made before resolving the problem.')),
                ('hints_used', models.PositiveIntegerField(default=0, help_text='Number of hints Albert handed out during the attempt.')),
                ('points_awarded', models.PositiveIntegerField(default=0, help_text='XP earned for solving this problem (0 when given up).')),
                ('star_rating', models.PositiveSmallIntegerField(default=0, help_text='Logic/approach quality shown by the student (1–5) when solved.')),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsa_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dsa_training',
                'ordering': ['-created_at'],
            },
        ),
    ]
