# Generated by Django 6.0.7 on 2026-09-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0045_groupdiscussiontraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdiscussiontraining',
            name='assessment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupdiscussiontraining',
            name='evaluations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='groupdiscussiontraining',
            name='intro_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='groupdiscussiontraining',
            name='phase',
            field=models.CharField(choices=[('intro', 'Introductions'), ('discussion', 'Discussion'), ('completed', 'Completed')], default='intro', max_length=20),
        ),
    ]
