# Generated by Django 6.0.7 on 2026-09-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0046_groupdiscussiontraining_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdiscussiontraining',
            name='intro_scripts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
