# Generated by Django 6.0.7 on 2026-09-16 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0047_groupdiscussiontraining_intro_scripts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, default='', help_text='Human-friendly unique id. Auto-generated when left blank.', max_length=30, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, default='', max_length=120)),
                ('company_description', models.TextField(blank=True, default='')),
                ('job_roles', models.JSONField(blank=True, default=list)),
                ('eligible_courses', models.JSONField(blank=True, default=list)),
                ('eligible_branches', models.JSONField(blank=True, default=list)),
                ('minimum_cgpa', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum CGPA required (on a 10-point scale).', max_digits=4, null=True)),
                ('maximum_backlogs', models.PositiveSmallIntegerField(blank=True, help_text='Maximum number of active backlogs allowed (0 = none).', null=True)),
                ('graduation_year', models.PositiveIntegerField(blank=True, help_text='Batch year eligible for the drive (e.g. 2026).', null=True)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum annual CTC in LPA.', max_digits=8, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum annual CTC in LPA.', max_digits=8, null=True)),
                ('work_location', models.CharField(blank=True, default='', max_length=255)),
                ('work_mode', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('field', 'Field / Outside')], default='onsite', max_length=20)),
                ('number_of_openings', models.PositiveIntegerField(blank=True, null=True)),
                ('selection_rounds', models.JSONField(blank=True, default=list)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('campus_visit_date', models.DateField(blank=True, null=True)),
                ('recruitment_status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Active / Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('placement_mode', models.CharField(choices=[('full_time', 'Full-time'), ('internship_ppo', 'Internship + PPO'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('offer_status', models.CharField(choices=[('pending', 'Pending'), ('offered', 'Offered'), ('on_hold', 'On Hold'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='The institution staff member who recorded this company.', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='TalentBroIns.clientprofile')),
                ('institution', models.ForeignKey(help_text='The institution the company is visiting for placements.', on_delete=django.db.models.deletion.CASCADE, related_name='company_records', to='TalentBroIns.institution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
