# Generated by Django 6.0.7 on 2026-09-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0048_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tier',
            field=models.CharField(choices=[('super_dream', 'Super Dream'), ('dream', 'Dream'), ('core', 'Core'), ('mass', 'Mass')], default='core', help_text='Hiring tier used by placement cells (CTC bracket based).', max_length=20),
        ),
    ]
