# Generated by Django 6.0.7 on 2026-09-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0052_profileupdatesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='translation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
