# Generated by Django 6.0.7 on 2026-09-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0053_chatmessage_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='preferred_language',
            field=models.CharField(blank=True, default='', help_text="The candidate's preferred language (e.g., English, Hindi, Bengali).", max_length=30),
        ),
    ]
