# Generated by Django 6.0.7 on 2026-09-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0054_alter_candidateprofile_preferred_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='work_experience',
        ),
    ]
