# Generated by Django 6.0.7 on 2026-09-18 13:59

from django.db import migrations, models


def copy_full_name_to_first_name(apps, schema_editor):
    """Move each candidate's existing full_name into first_name."""
    CandidateProfile = apps.get_model('TalentBroIns', 'CandidateProfile')
    CandidateProfile.objects.update(first_name=models.F('full_name'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0055_remove_candidateprofile_work_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.RunPython(
            copy_full_name_to_first_name,
            noop,
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='full_name',
        ),
    ]