# Generated by Django 6.0.7 on 2026-09-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0056_alter_candidateprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='college_email',
        ),
    ]
