# Generated by Django 6.0.7 on 2026-09-19 11:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0058_remove_groupdiscussiontraining'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GdTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('topic', models.TextField(blank=True, default='')),
                ('participants', models.JSONField(blank=True, default=list)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('phase', models.CharField(choices=[('intro', 'Introductions'), ('discussion', 'Discussion'), ('completed', 'Completed')], default='discussion', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=15, help_text='How long the discussion is meant to run before it auto-ends.')),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('content_quality', models.PositiveSmallIntegerField(default=0, help_text='Content Quality score (0-100).')),
                ('reasoning', models.PositiveSmallIntegerField(default=0, help_text='Reasoning score (0-100).')),
                ('communication', models.PositiveSmallIntegerField(default=0, help_text='Communication score (0-100).')),
                ('confidence', models.PositiveSmallIntegerField(default=0, help_text='Confidence score (0-100).')),
                ('teamwork', models.PositiveSmallIntegerField(default=0, help_text='Teamwork score (0-100).')),
                ('initiative', models.PositiveSmallIntegerField(default=0, help_text='Initiative score (0-100).')),
                ('active_listening', models.PositiveSmallIntegerField(default=0, help_text='Active Listening score (0-100).')),
                ('build_challenge', models.PositiveSmallIntegerField(default=0, help_text='Build / Challenge score (0-100).')),
                ('overall_score', models.PositiveSmallIntegerField(default=0, help_text='Overall GD score (0-100).')),
                ('grade', models.CharField(blank=True, default='', help_text='Overall grade (Excellent, Good, Average, Poor).', max_length=10)),
                ('overall_summary', models.TextField(blank=True, default='', help_text="AI narrative summary of the student's performance.")),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvement_areas', models.JSONField(blank=True, default=list)),
                ('evaluations', models.JSONField(blank=True, default=list)),
                ('assessment', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gd_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gd_training',
                'ordering': ['-created_at'],
            },
        ),
    ]
