# Generated by Django 6.0.7 on 2026-09-20 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0059_gdtraining'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishTrainingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, help_text='When this session ended and its transcript was locked so the analysis could be generated.', null=True)),
                ('clarity', models.PositiveSmallIntegerField(default=0, help_text='Clarity of the message score (0–100).')),
                ('structure', models.PositiveSmallIntegerField(default=0, help_text='Structure and organisation score (0–100).')),
                ('grammar', models.PositiveSmallIntegerField(default=0, help_text='Grammar score (0–100).')),
                ('vocabulary', models.PositiveSmallIntegerField(default=0, help_text='Vocabulary and word choice score (0–100).')),
                ('spelling', models.PositiveSmallIntegerField(default=0, help_text='Spelling and punctuation score (0–100).')),
                ('conciseness', models.PositiveSmallIntegerField(default=0, help_text='Conciseness score (0–100).')),
                ('task_focus', models.PositiveSmallIntegerField(default=0, help_text='Task focus and format score (0–100).')),
                ('professional_tone', models.PositiveSmallIntegerField(default=0, help_text='Professional tone score (0–100).')),
                ('writing_score', models.PositiveSmallIntegerField(default=0, help_text='Overall English writing score (0–100).')),
                ('mistakes', models.JSONField(blank=True, default=list)),
                ('recurring_mistakes', models.TextField(blank=True, default='')),
                ('strengths', models.TextField(blank=True, default='')),
                ('areas_for_improvement', models.TextField(blank=True, default='')),
                ('ai_recommendations', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'english_training_session',
                'ordering': ['-created_at'],
            },
        ),
    ]
