# Generated by Django 6.0.7 on 2026-09-20 17:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0060_english_training_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='cost_incurred',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Total Gemini cost incurred by this candidate in INR (including 40% markup).', max_digits=12),
        ),
    ]
