# Generated by Django 6.0.7 on 2026-09-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0061_add_candidate_cost_incurred'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='readiness_components',
            field=models.JSONField(blank=True, default=dict, help_text='Flattened readiness pillar breakdown (mock/self-training/chat/CGPA/modules).'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='readiness_department_rank',
            field=models.PositiveIntegerField(blank=True, help_text='Rank of this candidate among same-department peers in their college.', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='readiness_department_total',
            field=models.PositiveIntegerField(default=0, help_text='Number of same-department peers (with any readiness signal) ranked.'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='readiness_overall_rank',
            field=models.PositiveIntegerField(blank=True, help_text='All Institute Rank (AIR) of this candidate within their own college.', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='readiness_overall_total',
            field=models.PositiveIntegerField(default=0, help_text='Number of college peers (with any readiness signal) in the AIR ranking.'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='readiness_score',
            field=models.FloatField(blank=True, help_text='Composite TalentBro Readiness Score (0–100) for this candidate.', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='readiness_updated_at',
            field=models.DateTimeField(blank=True, help_text="When this candidate's readiness score and ranks were last recomputed.", null=True),
        ),
    ]
