# Generated by Django 6.0.7 on 2026-09-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0062_add_candidate_readiness_ranks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='readiness_components',
            field=models.JSONField(blank=True, default=dict, help_text='Flattened readiness pillar breakdown (mock/self-training/chat/modules).'),
        ),
    ]
