# Generated by Django 6.0.7 on 2026-09-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0063_alter_candidateprofile_readiness_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='readiness_department_total',
            field=models.PositiveIntegerField(default=0, help_text="Number of students in this candidate's department (full roll) ranked."),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='readiness_overall_total',
            field=models.PositiveIntegerField(default=0, help_text="Number of students in this candidate's college (full roll) in the AIR denominator."),
        ),
    ]
