# Generated by Django 6.0.7 on 2026-09-22 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0065_add_candidateprofile_time_spent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, help_text='Stable unique key so repeated completion events create only one notification.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='When set, this notice is delivered only to this user. Broadcasts leave it unset.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='redirect_path',
            field=models.CharField(blank=True, default='', help_text='Frontend route to open when the user taps the notification.', max_length=500),
        ),
    ]
