# Generated by Django 6.0.7 on 2026-09-25 03:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0066_notification_dedupe_key_notification_recipient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRoadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('timeline_target', models.CharField(blank=True, default='', help_text='Raw timeline goal, e.g. "placement prepared by the end of this month".', max_length=255)),
                ('target_date', models.DateField(blank=True, help_text='Normalised target deadline (ISO date) when the goal maps to a concrete date.', null=True)),
                ('company_target', models.JSONField(blank=True, default=list, help_text='Companies the candidate wants to get placed in (e.g. ["TCS", "Accenture"]).')),
                ('goal_statement', models.TextField(blank=True, default='', help_text='Paraphrased, unambiguous statement of the placement goal.')),
                ('mocks_required', models.PositiveIntegerField(default=0, help_text='Number of mock interviews recommended before the placement drive.')),
                ('daily_practice_session_duration', models.PositiveIntegerField(default=0, help_text='Recommended daily practice-session duration in minutes.')),
                ('self_training_required', models.JSONField(blank=True, default=dict, help_text='Per-module self-training requirements: {module: {required, sessions_per_week, focus_areas}}.')),
                ('roadmap', models.JSONField(blank=True, default=dict, help_text='Comprehensive plan — phased weeks, topics and a weekly schedule.')),
                ('summary', models.TextField(blank=True, default='', help_text='Natural-language summary of the generated roadmap.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_session', models.ForeignKey(blank=True, help_text='The chat session the roadmap was last generated from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap', to='TalentBroIns.chatsession')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_roadmap', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
