# Generated by Django 6.0.7 on 2026-09-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0068_institutionsresume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionsresume',
            name='file',
        ),
        migrations.AddField(
            model_name='institutionsresume',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
