# Generated by Django 6.0.7 on 2026-09-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0069_remove_institutionsresume_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='mock_interview_department_rank',
            field=models.PositiveIntegerField(blank=True, help_text='Rank among same-department peers in the mock-interview cohort.', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='mock_interview_department_total',
            field=models.PositiveIntegerField(default=0, help_text='Department size of the mock-interview ranking cohort.'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='mock_interview_rank',
            field=models.PositiveIntegerField(blank=True, help_text='Rank among the college candidates who have a mock-interview score.', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='mock_interview_score',
            field=models.FloatField(blank=True, help_text='Moderated Mock Interview score (0–100) for this candidate.', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='mock_interview_total',
            field=models.PositiveIntegerField(default=0, help_text='Number of college candidates in the mock-interview ranking cohort.'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='self_training_department_rank',
            field=models.PositiveIntegerField(blank=True, help_text='Rank among same-department peers in the self-training cohort.', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='self_training_department_total',
            field=models.PositiveIntegerField(default=0, help_text='Department size of the self-training ranking cohort.'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='self_training_rank',
            field=models.PositiveIntegerField(blank=True, help_text='Rank among the college candidates who have a self-training score.', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='self_training_score',
            field=models.FloatField(blank=True, help_text='Moderated Self-Training score (0–100) for this candidate.', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='self_training_total',
            field=models.PositiveIntegerField(default=0, help_text='Number of college candidates in the self-training ranking cohort.'),
        ),
        migrations.AlterField(
            model_name='mockinterview',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('not_scored', 'Not Scored — Not Enough Answers')], default='active', max_length=20),
        ),
    ]
