# Generated by Django 6.0.7 on 2026-09-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0073_dailytarget_module_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text="The candidate's professional headline. Filled in from their LinkedIn headline, and editable by the candidate afterwards.", max_length=500),
        ),
    ]
