# Generated by Django 6.0.7 on 2026-09-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0074_candidateprofile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyTarget',
        ),
    ]
