# Generated by Django 6.0.7 on 2026-09-28 04:24

from django.db import migrations, models


def clear_eligibility_overrides(apps, schema_editor):
    """Hand every existing student back to the readiness rule.

    ``placement_eligible`` used to be a stored verdict defaulting to True, so
    essentially the whole batch carried a pinned True that would have frozen it
    as eligible forever under the new nullable-override semantics. Clearing the
    column to NULL is what actually hands control to the readiness rule.

    This is deliberately irreversible in practice: the previous values are not
    recoverable, only the previous default is.
    """
    CandidateProfile = apps.get_model('TalentBroIns', 'CandidateProfile')
    CandidateProfile.objects.exclude(placement_eligible=None).update(
        placement_eligible=None,
    )


def restore_default_eligibility(apps, schema_editor):
    """Reverse step: put the old default back on every row."""
    CandidateProfile = apps.get_model('TalentBroIns', 'CandidateProfile')
    CandidateProfile.objects.filter(placement_eligible=None).update(
        placement_eligible=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0075_delete_dailytarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='placement_eligible',
            field=models.BooleanField(blank=True, default=None, help_text='Leave blank to follow the readiness rule (score >= 40). Set Yes to force a student eligible or No to force them ineligible regardless of their readiness score.', null=True, verbose_name='Placement eligible (override)'),
        ),
        # Must run after AlterField: the column is NOT NULL until that lands.
        migrations.RunPython(
            clear_eligibility_overrides,
            reverse_code=restore_default_eligibility,
        ),
    ]
