# Generated by Django 6.0.7 on 2026-09-28 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0076_alter_candidateprofile_placement_eligible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. TCS Campus Drive 2026.', max_length=255)),
                ('roles', models.JSONField(blank=True, default=list, help_text='Roles launched by this drive, each {"title", "description", "vacancies"}.')),
                ('total_vacancies', models.PositiveIntegerField(blank=True, help_text='Total openings across every role. Left blank to sum the roles.', null=True)),
                ('drive_mode', models.CharField(choices=[('campus', 'On Campus'), ('virtual', 'Virtual Drive'), ('off_campus', 'Off Campus')], default='campus', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Active / Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('visit_date', models.DateField(blank=True, help_text='Date the company visits the campus.', null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('work_mode', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('field', 'Field / Outside')], default='onsite', max_length=20)),
                ('work_location', models.CharField(blank=True, default='', max_length=255)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum annual CTC in LPA.', max_digits=8, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum annual CTC in LPA.', max_digits=8, null=True)),
                ('eligible_branches', models.JSONField(blank=True, default=list)),
                ('eligible_courses', models.JSONField(blank=True, default=list)),
                ('minimum_cgpa', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum CGPA required (on a 10-point scale).', max_digits=4, null=True)),
                ('maximum_backlogs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('graduation_year', models.PositiveIntegerField(blank=True, help_text='Batch year eligible for the drive (e.g. 2026).', null=True)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('selection_rounds', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='', help_text='Anything else students should know about the visit.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='The company visiting the institution.', on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='TalentBroIns.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='The staff account that scheduled this drive.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drives_created', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(help_text='The institution hosting the drive.', on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='TalentBroIns.institution')),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
