# Generated by Django 6.0.7 on 2026-09-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0077_drive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='number_of_openings',
        ),
    ]
