# Generated by Django 6.0.7 on 2026-09-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0078_remove_company_number_of_openings'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='extracurricular_activities',
            field=models.TextField(blank=True, default='', help_text='Extracurricular activities, clubs, competitions, events and volunteering done outside the classroom.'),
        ),
    ]
