# Generated by Django 6.0.7 on 2026-09-28 07:55

import json
import re

from django.db import migrations, models

SEPARATORS = re.compile(r"[\n,]")


def text_to_list(apps, schema_editor):
    """Rewrite every row as a JSON list before the column type changes, so the
    text already stored (and SQLite's JSON_VALID check on the rebuilt table) both
    come out right. An empty string becomes an empty list, not a bad value."""
    CandidateProfile = apps.get_model("TalentBroIns", "CandidateProfile")
    for profile in CandidateProfile.objects.all().iterator():
        raw = profile.extracurricular_activities
        if isinstance(raw, list):
            continue
        text = raw or ""
        # A client that sent the list as a JSON string left the quotes and the
        # escaped newlines in the text, so unwrap it before splitting.
        if text.startswith('"'):
            try:
                text = json.loads(text)
            except ValueError:
                text = text.strip('"')
        items = [part.strip() for part in SEPARATORS.split(text) if part.strip()]
        CandidateProfile.objects.filter(pk=profile.pk).update(
            extracurricular_activities=json.dumps(items)
        )


def list_to_text(apps, schema_editor):
    """Re-flatten the list back into the newline-separated text."""
    CandidateProfile = apps.get_model("TalentBroIns", "CandidateProfile")
    for profile in CandidateProfile.objects.all().iterator():
        items = profile.extracurricular_activities
        if not isinstance(items, list):
            continue
        CandidateProfile.objects.filter(pk=profile.pk).update(
            extracurricular_activities="\n".join(items)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0079_candidateprofile_extracurricular_activities'),
    ]

    operations = [
        migrations.RunPython(text_to_list, list_to_text),
        migrations.AlterField(
            model_name='candidateprofile',
            name='extracurricular_activities',
            field=models.JSONField(blank=True, default=list, help_text='Clubs, competitions, events and volunteering the candidate took part in outside the classroom, one entry per item.'),
        ),
    ]
