# Generated by Django 6.0.7 on 2026-09-29 02:19
#
# A Company is the standing recruiter relationship; a Drive is the hiring event.
# The ten fields that described a specific hiring move from Company to Drive,
# which already owned most of them. The data migration below copies what was on
# each company onto the drives that company already has, so no recorded hiring
# detail is lost. Company rows with no Drive at all are left with nothing to
# copy to - the values die with the column, which is the intent.

from django.db import migrations, models


def copy_hiring_fields_to_drives(apps, schema_editor):
    """Copy each company's hiring fields onto the drives already recorded for it.

    Drive.roles is a list of {"title", "description", "vacancies"} objects while
    Company.job_roles was a flat list of role names, so the roles are converted
    rather than assigned. Fields Drive already had (work_mode, application
    deadline, selection rounds, required skills) are only filled in where the
    drive left them blank, so an explicitly set value on the drive wins.
    """
    Company = apps.get_model('TalentBroIns', 'Company')
    Drive = apps.get_model('TalentBroIns', 'Drive')

    company_fields = [
        f.name for f in Company._meta.get_fields()
        if f.name in {
            'job_roles', 'work_mode', 'required_skills', 'preferred_skills',
            'application_deadline', 'campus_visit_date', 'selection_rounds',
            'recruitment_status', 'placement_mode', 'offer_status',
        }
    ]
    if not company_fields:
        # Already applied (or a fresh database built straight from the models).
        return

    for company in Company.objects.all().prefetch_related('drives'):
        drives = list(company.drives.all())
        if not drives:
            continue
        for drive in drives:
            drive.status = company.recruitment_status or drive.status
            drive.work_mode = company.work_mode or drive.work_mode
            drive.application_deadline = (
                company.application_deadline or drive.application_deadline
            )
            drive.visit_date = company.campus_visit_date or drive.visit_date
            drive.placement_mode = company.placement_mode or drive.placement_mode
            drive.offer_status = company.offer_status or drive.offer_status
            if not drive.selection_rounds and company.selection_rounds:
                drive.selection_rounds = list(company.selection_rounds)
            if not drive.required_skills and company.required_skills:
                drive.required_skills = list(company.required_skills)
            if not drive.preferred_skills and company.preferred_skills:
                drive.preferred_skills = list(company.preferred_skills)
            if not drive.roles and company.job_roles:
                # Flat role names become the title of an entry with no vacancy
                # count, which leaves Drive.vacancies to fall back to the sum.
                drive.roles = [
                    {'title': str(role), 'description': '', 'vacancies': 0}
                    for role in company.job_roles
                ]
            drive.save()


def noop(apps, schema_editor):
    """Reverse pass: the values live on Drive now and Company no longer has
    columns to put them back in. Left deliberately inert rather than restoring
    a lossy guess."""


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0080_candidateprofile_extracurricular_activities_json'),
    ]

    operations = [
        # Add the three Drive columns first so the backfill below has somewhere
        # to write, then move the data, and only then drop the Company columns.
        migrations.AddField(
            model_name='drive',
            name='offer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('offered', 'Offered'), ('on_hold', 'On Hold'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='drive',
            name='placement_mode',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('internship_ppo', 'Internship + PPO'), ('contract', 'Contract')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='drive',
            name='preferred_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(copy_hiring_fields_to_drives, noop),
        migrations.RemoveField(
            model_name='company',
            name='application_deadline',
        ),
        migrations.RemoveField(
            model_name='company',
            name='campus_visit_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='job_roles',
        ),
        migrations.RemoveField(
            model_name='company',
            name='offer_status',
        ),
        migrations.RemoveField(
            model_name='company',
            name='placement_mode',
        ),
        migrations.RemoveField(
            model_name='company',
            name='preferred_skills',
        ),
        migrations.RemoveField(
            model_name='company',
            name='recruitment_status',
        ),
        migrations.RemoveField(
            model_name='company',
            name='required_skills',
        ),
        migrations.RemoveField(
            model_name='company',
            name='selection_rounds',
        ),
        migrations.RemoveField(
            model_name='company',
            name='work_mode',
        ),
    ]
