# Generated by Django 6.0.7 on 2026-09-29 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0081_move_hiring_fields_from_company_to_drive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='placement_eligible',
        ),
    ]
