# Generated by Django 6.0.7 on 2026-09-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0082_remove_candidateprofile_placement_eligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='placement_status',
            field=models.CharField(choices=[('not_started', 'Ineligible'), ('applying', 'Applying'), ('shortlisted', 'Shortlisted'), ('placed', 'Placed')], default='not_started', max_length=30),
        ),
    ]
