# Generated by Django 6.0.7 on 2026-09-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0084_drive_single_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_ai_info',
            field=models.JSONField(blank=True, default=list, help_text='Gemini-generated company profile blocks: [{"name", "short_desc", "known_for", "big_desc"}].'),
        ),
    ]
