# Generated by Django 6.0.7 on 2026-09-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0085_company_company_ai_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterviewanalysis',
            name='ada',
            field=models.CharField(blank=True, default='', help_text='Name of the panelist recorded for Ada (Analytical & Logical Thinking).', max_length=255),
        ),
        migrations.AddField(
            model_name='mockinterviewanalysis',
            name='albert',
            field=models.CharField(blank=True, default='', help_text='Name of the panelist recorded for Albert (Technical Architect).', max_length=255),
        ),
        migrations.AddField(
            model_name='mockinterviewanalysis',
            name='carl',
            field=models.CharField(blank=True, default='', help_text='Name of the panelist recorded for Carl (Behavioral Intelligence).', max_length=255),
        ),
        migrations.AddField(
            model_name='mockinterviewanalysis',
            name='daniel',
            field=models.CharField(blank=True, default='', help_text='Name of the panelist recorded for Daniel (Decision Science).', max_length=255),
        ),
        migrations.AddField(
            model_name='mockinterviewanalysis',
            name='maya',
            field=models.CharField(blank=True, default='', help_text='Name of the panelist recorded for Maya (Communication & HR).', max_length=255),
        ),
        migrations.AddField(
            model_name='mockinterviewanalysis',
            name='peter',
            field=models.CharField(blank=True, default='', help_text='Name of the panelist recorded for Peter (Management & Leadership).', max_length=255),
        ),
    ]
