# Generated by Django 6.0.7 on 2026-09-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0087_clientprofile_user_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='id_verified',
        ),
    ]
