# Generated by Django 6.0.7 on 2026-09-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0090_remove_institution_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.CharField(blank=True, default='', help_text='Absolute URL of the company favicon, derived from the website.', max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, default='', help_text='Company website or homepage, as provided.', max_length=255),
        ),
    ]
