# Generated by Django 6.0.7 on 2026-10-03 19:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0092_clientchatsession_clientchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.CharField(choices=[('placement_cell', 'Placement Cell'), ('platform', 'TalentBro Platform'), ('forum', 'Discussion Forum')], max_length=30),
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(help_text='The post text. Plain text only — no markup, no attachments.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='The candidate profile that wrote this post.', on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='TalentBroIns.candidateprofile')),
                ('institution', models.ForeignKey(help_text='The college this post belongs to. Scopes the whole forum.', on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='TalentBroIns.institution')),
            ],
            options={
                'db_table': 'forum_post',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
