# Generated by Django 6.0.7 on 2026-10-05 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0093_alter_notification_sender_forumpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_down', models.BooleanField(default=False, help_text='While ticked, every page except the home page is replaced with the downtime page. Unticked means the site is serving normally.', verbose_name='Site is down')),
                ('message', models.CharField(blank=True, default='', help_text="Shown on the downtime page. Left blank, 'We are carrying out scheduled maintenance on TalentBro. The site will be back shortly.' is used instead.", max_length=300, verbose_name='Downtime message')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='The staff member who last flipped the switch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site availability',
                'verbose_name_plural': 'Site availability',
                'db_table': 'site_setting',
            },
        ),
    ]
