"""The training targets a placement officer launches for their college.

One row per target rather than one row per student, so a department-wide or
hand-picked target is a single commitment that can be read back, closed or
withdrawn as a unit. The students it covers hang off the `candidates`
many-to-many; a target scoped by department stores that name and resolves the
students at read time.
"""

# Generated by Django 6.0.7 on 2026-10-05 18:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0094_sitesetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_Target',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='What this target is called on the board, e.g. "CSE DSA sprint".', max_length=255)),
                ('department', models.CharField(blank=True, default='', help_text='Department this target covers, matched against CandidateProfile.department. Leave blank for a campus-wide target.', max_length=120)),
                ('communication_count', models.PositiveIntegerField(default=0, help_text='How many Communication Skills items are targeted.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('group_discussion_count', models.PositiveIntegerField(default=0, help_text='How many Group Discussion items are targeted.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('aplr_count', models.PositiveIntegerField(default=0, help_text='How many APLR items are targeted.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('basic_math_count', models.PositiveIntegerField(default=0, help_text='How many Mathematics items are targeted.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('english_count', models.PositiveIntegerField(default=0, help_text='How many English Trainer items are targeted.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('situational_count', models.PositiveIntegerField(default=0, help_text='How many Situational Problem Solving items are targeted.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('technical_count', models.PositiveIntegerField(default=0, help_text='How many Technical problem-solving items are targeted.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('dsa_count', models.PositiveIntegerField(default=0, help_text='How many DSA items are targeted.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mock_interview_count', models.PositiveIntegerField(default=0, help_text='How many mock interviews are targeted.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('starts_on', models.DateField(blank=True, help_text='Day the target starts counting from. Blank means it starts today.', null=True)),
                ('due_on', models.DateField(help_text='Day the target is judged against.')),
                ('notes', models.TextField(blank=True, default='', help_text='Anything the officer wants beside the numbers, e.g. how to prepare.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidates', models.ManyToManyField(blank=True, help_text='Specific students this target covers, alongside the department.', related_name='students_targets', to='TalentBroIns.candidateprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_targets_created', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(help_text='The college this target belongs to. Scopes the whole board.', on_delete=django.db.models.deletion.CASCADE, related_name='students_targets', to='TalentBroIns.institution')),
            ],
            options={
                'verbose_name': 'Student target',
                'verbose_name_plural': 'Student targets',
                'db_table': 'students_target',
                'ordering': ['-created_at'],
            },
        ),
    ]
