# Generated by Django 6.0.7 on 2026-10-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentBroIns', '0095_students_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='client_targets',
            field=models.JSONField(blank=True, default=dict, help_text="This candidate's progress against the training targets their institution has set, keyed by target id. Written by `sync_client_targets()` — never by hand. Empty when no target covers this candidate."),
        ),
    ]
