"""
Django settings for TalentBro project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# ===========================================================================
#  TALENTBRO BUSINESS MODEL  (for future reference — the core of the platform)
# ===========================================================================
#
#  The platform exists to close the GAP between two things that rarely meet
#  before a drive happens:
#
#    1) WHAT KIND OF STUDENTS an institution actually has
#       → skills, CGPA, branches, courses, placement readiness, expected CTC,
#         verification status, preferred roles/locations, backlogs tolerance,
#         and every placement-relevant attribute captured in the profile.
#    2) WHAT COMPANIES ACTUALLY NEED during a drive
#       → eligibility (min CGPA, backlogs, branch/course), roles, CTC band,
#         required vs preferred skills, selection rounds, deadlines, openings.
#
#  We keep both sides in ONE database so the placement department can see, at
#  a glance, which students genuinely qualify for every visiting company. The
#  placement team then:
#
#      • shortlists only the ACTUALLY ELIGIBLE students for a drive, and
#      • puts the best-fit candidates FRONT OF THE QUEUE for that company,
#
#  so the institution stops wasting a company's time with ineligible bulk
#  shortlists and starts converting real placements. That understanding is the
#  product: eligibility match, per-drive eligible-pool counts, and readouts of
#  "our students vs what the company asks".
#
#  THE PLATFORM HAS EXACTLY TWO SIDES — no third role.
#
#    1. CLIENT  (institution people / placement cell)
#       Owns an Institution + their ClientProfile. Sees the dashboards
#       (overview, students, companies, drives, reports), records Companies,
#       creates drives and manages shortlists. Access is Beta (read-only) or
#       Master (full).
#
#    2. STUDENT / CANDIDATE  (the learners being placed)
#       Owns a CandidateProfile (candidate == student in this project). Fills
#       their own profile, trains with TalentBro (chat, mock interviews, GD,
#       communication, DSA, APLR, etc.) and applies to drives.
#
#  One account = one side, derived from the user's profile (see user_role());
#  the same auth User model backs both sides.
# ===========================================================================

import os
from pathlib import Path

# Load environment variables from the project .env file (GitHub Actions,
# docker-compose, or shell env may instead supply the same variables directly).
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p6(!=nvzhn80-s56rg^8h9l_9%n&4syc(=ut4&u=%p*9knpf2m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Hosts this process will answer for. Replaces ALLOWED_HOSTS = ['*'].
#
# Django strips the port before matching (django/http/request.py:195 calls
# split_domain_port and validates only the domain half), so the bare hostnames
# below already cover every port - never add "localhost:8000" style entries,
# they can never match. "testserver" is not needed either; Django's test
# runner appends it to ALLOWED_HOSTS itself.
#
# The leading-dot form is deliberately not used. ".talentbro.in" would be
# tidier but would also admit any forgotten staging or preview subdomain, which
# is the same class of exposure as the old CORS_ALLOW_ALL_ORIGINS.
ALLOWED_HOSTS = [
    # Production - the institutions SPA and this API
    'talentbro.in',
    'www.talentbro.in',
    'ins.talentbro.in',
    'ins-api.talentbro.in',
    # Local development
    'localhost',
    '127.0.0.1',
    '[::1]',
    '0.0.0.0',
]
# If the student-facing API turns out to be served by this same process, add
# 'api.talentbro.in' to the list above.

# Escape hatch for hosts that cannot be known when this file is written -
# preview deploys, a bare public IP. Comma separated, no spaces needed:
#   ALLOWED_HOSTS=203.0.113.7,my-branch.preview.example
# Entries here are appended to the list above, never a replacement for it.
_extra_allowed_hosts = [
    host.strip() for host in os.environ.get('ALLOWED_HOSTS', '').split(',') if host.strip()
]
if _extra_allowed_hosts:
    ALLOWED_HOSTS += _extra_allowed_hosts

# Voice recordings are uploaded as raw audio (WAV) for transcription. Keep them
# under the backend's per-request memory cap so transcription never 400s.
DATA_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024


# Application definition

# NOTE: In this entire project, candidates and students are the SAME thing.
# A student is a candidate (a CandidateProfile is the student's profile). The
# old StudentProfile model was merged into CandidateProfile. There is exactly
# one Role per user: 'student' (candidate) or 'institution_staff'.

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'TalentBroIns',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TalentBro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TalentBro.wsgi.application'


# CORS - only the origins the SPAs are actually served from

# Was CORS_ALLOW_ALL_ORIGINS = True. Combined with CORS_ALLOW_CREDENTIALS that
# made django-cors-headers reflect *any* caller's Origin back with
# Access-Control-Allow-Credentials: true, so any site could make credentialed
# calls to the API and read the responses. The explicit list keeps every host
# that works today and closes that off. CSRF_TRUSTED_ORIGINS below restricts
# the same set for unsafe methods; the two should be kept in step.
CORS_ALLOWED_ORIGINS = [
    'https://talentbro.in',
    'https://www.talentbro.in',
    'https://ins.talentbro.in',
    'http://localhost:8080',
    'http://127.0.0.1:8080',
    'http://localhost:8081',
    'http://127.0.0.1:8081',
    # Django serving the admin itself (runserver default port), so a SPA on
    # :8080 can talk to an API on :8000 during local development.
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://[::1]:8000',
    'http://[::1]:8080',
    'http://[::1]:8081',
]
CORS_ALLOW_CREDENTIALS = True

# Origins allowed to make CSRF-protected (POST) calls from the SPA frontend.
CSRF_TRUSTED_ORIGINS = [
    'https://talentbro.in',
    'https://www.talentbro.in',
    'https://ins.talentbro.in',
    'http://localhost:8080',
    'http://127.0.0.1:8080',
    'http://localhost:8081',
    'http://127.0.0.1:8081',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://[::1]:8000',
    'http://[::1]:8080',
    'http://[::1]:8081',
]


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Sessions - keep authenticated users signed in for two weeks

SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # 14 days
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # survive browser restarts
SESSION_SAVE_EVERY_REQUEST = True  # sliding: extend the window on every visit

# The SPA (ins.talentbro.in) calls the API (ins-api.talentbro.in) cross-origin.
# The frontend echoes the `csrftoken` back in the X-CSRFToken header (see
# Frontend/src/lib/api.ts), so the cookie has to be scoped to the shared parent
# domain — a host-only cookie on ins-api is still sent back to the API, but it is
# invisible to the page's own JS, so the header is silently omitted and every
# POST fails with "Forbidden (CSRF token missing.)". The two hosts are same-site
# (both under talentbro.in), so the default SameSite=Lax still rides along on the
# fetch; only the domain scope and the Secure flag matter.
#
# This is the PRODUCTION configuration, so it is also the default. It is
# deliberately NOT derived from DEBUG: DEBUG is hardcoded True above, and keying
# the cookie settings off it silently strips the parent-domain scope on the
# deployed server, reintroducing exactly the failure above.
#
# Local development over plain http opts out with SECURE_COOKIES=false in
# Backend/.env, because the production settings are actively harmful there:
#   * CSRF_COOKIE_SECURE=True makes the browser refuse to store or send
#     `csrftoken` on http://localhost, so every POST died with
#     "Forbidden (CSRF cookie not set.)" - the cookie never reached Django.
#   * CSRF_COOKIE_DOMAIN='.talentbro.in' does not domain-match localhost, so the
#     browser drops the csrf and session cookies outright and the login session
#     would not survive the redirect.
SECURE_COOKIES = os.environ.get('SECURE_COOKIES', 'true').strip().lower() in (
    '1', 'true', 'yes', 'on',
)

# The `.strip() or ...` matters: a bare `COOKIE_DOMAIN=` line in .env sets the
# variable to an empty string, which is not the same as leaving it unset —
# `os.environ.get('COOKIE_DOMAIN', '.talentbro.in')` would return '' and emit a
# valueless `Domain=` attribute, which browsers discard, quietly giving us the
# host-only cookie this setting exists to prevent.
_cookie_domain = os.environ.get('COOKIE_DOMAIN', '').strip() or '.talentbro.in'

# Parent-domain scoping only applies to the production cookie set; on localhost
# such a cookie is a domain mismatch and the browser rejects it.
CSRF_COOKIE_DOMAIN = _cookie_domain if SECURE_COOKIES else None
CSRF_COOKIE_SECURE = SECURE_COOKIES
SESSION_COOKIE_DOMAIN = CSRF_COOKIE_DOMAIN
SESSION_COOKIE_SECURE = SECURE_COOKIES

# CSRF_COOKIE_HTTPONLY may be set True in production: /api/auth/csrf/ hands the
# token to the SPA in the response body, so no page script needs to read the
# cookie. Left False so a client that still reads document.cookie keeps working.

# TLS is terminated by the reverse proxy in front of this app, so the socket
# Django sees is plain http. Without this, request.is_secure() is False even for
# genuine https traffic, which breaks the CSRF referer check and any
# SECURE_SSL_REDIRECT added later. Must be a two-value tuple - Django raises
# ImproperlyConfigured otherwise (django/http/request.py:311).
# Security note: this trusts the header, so it is only safe while the app is
# reachable *through* the proxy and not directly. If the uvicorn port is
# exposed to the internet, a client can spoof X-Forwarded-Proto: https.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Gemini — credentials sourced from C:\Anirban\Yaadly\Backend\.env
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '').strip()
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-2.5-flash-lite').strip()
# Dedicated Gemini 2.5 model for speech-to-text transcription (voice-mic in
# chat). Full 2.5 models accept audio input; also self-verifies the transcript.
GEMINI_STT_MODEL = os.environ.get('GEMINI_STT_MODEL', 'gemini-2.5-flash').strip()
# Dedicated model for mock interview conduction only.
GEMINI_MOCK_INTERVIEW_MODEL = os.environ.get(
    'GEMINI_MOCK_INTERVIEW_MODEL', 'gemini-3.1-flash-lite',
).strip()
# Dedicated model for the AI-powered student onboarding flow.
GEMINI_ONBOARDING_MODEL = os.environ.get(
    'GEMINI_ONBOARDING_MODEL', 'gemini-2.5-flash-lite',
).strip()

# Groq Whisper OCR — free-tier speech-to-text used for voice training
# transcription. If unset, the backend falls back to Gemini audio transcription.
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '').strip()
GROQ_MODEL = os.environ.get('GROQ_MODEL', 'whisper-large-v3-turbo').strip()

# LinkedIn profile scraping via Apify. Used by the candidate "Complete profile"
# flow (photo + headline) and by the resume builder (the whole profile).
APIFY_TOKEN = os.environ.get('APIFY_TOKEN', '').strip()
# Which Apify actor to scrape with. The default, calm_builder~linkedin-profile-
# scraper, reads only what LinkedIn shows logged-out visitors, so it needs no
# session cookies but returns fewer sections (no certifications, skills, projects
# or languages). Point this at a richer signed-in actor, and supply its cookies,
# if a resume needs the full section set.
APIFY_LINKEDIN_ACTOR = os.environ.get(
    'APIFY_LINKEDIN_ACTOR', 'calm_builder~linkedin-profile-scraper',
).strip()
