"""
Django settings for TalentBro project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# ===========================================================================
#  TALENTBRO BUSINESS MODEL  (for future reference — the core of the platform)
# ===========================================================================
#
#  The platform exists to close the GAP between two things that rarely meet
#  before a drive happens:
#
#    1) WHAT KIND OF STUDENTS an institution actually has
#       → skills, CGPA, branches, courses, placement readiness, expected CTC,
#         verification status, preferred roles/locations, backlogs tolerance,
#         and every placement-relevant attribute captured in the profile.
#    2) WHAT COMPANIES ACTUALLY NEED during a drive
#       → eligibility (min CGPA, backlogs, branch/course), roles, CTC band,
#         required vs preferred skills, selection rounds, deadlines, openings.
#
#  We keep both sides in ONE database so the placement department can see, at
#  a glance, which students genuinely qualify for every visiting company. The
#  placement team then:
#
#      • shortlists only the ACTUALLY ELIGIBLE students for a drive, and
#      • puts the best-fit candidates FRONT OF THE QUEUE for that company,
#
#  so the institution stops wasting a company's time with ineligible bulk
#  shortlists and starts converting real placements. That understanding is the
#  product: eligibility match, per-drive eligible-pool counts, and readouts of
#  "our students vs what the company asks".
#
#  THE PLATFORM HAS EXACTLY TWO SIDES — no third role.
#
#    1. CLIENT  (institution people / placement cell)
#       Owns an Institution + their ClientProfile. Sees the dashboards
#       (overview, students, companies, drives, reports), records Companies,
#       creates drives and manages shortlists. Access is Beta (read-only) or
#       Master (full).
#
#    2. STUDENT / CANDIDATE  (the learners being placed)
#       Owns a CandidateProfile (candidate == student in this project). Fills
#       their own profile, trains with TalentBro (chat, mock interviews, GD,
#       communication, DSA, APLR, etc.) and applies to drives.
#
#  One account = one side, derived from the user's profile (see user_role());
#  the same auth User model backs both sides.
# ===========================================================================

import os
from pathlib import Path

# Load environment variables from the project .env file (GitHub Actions,
# docker-compose, or shell env may instead supply the same variables directly).
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p6(!=nvzhn80-s56rg^8h9l_9%n&4syc(=ut4&u=%p*9knpf2m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['ins-api.talentbro.in', 'ins.talentbro.in']

# Voice recordings are uploaded as raw audio (WAV) for transcription. Keep them
# under the backend's per-request memory cap so transcription never 400s.
DATA_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024


# Application definition

# NOTE: In this entire project, candidates and students are the SAME thing.
# A student is a candidate (a CandidateProfile is the student's profile). The
# old StudentProfile model was merged into CandidateProfile. There is exactly
# one Role per user: 'student' (candidate) or 'institution_staff'.

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'TalentBroIns',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TalentBro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TalentBro.wsgi.application'


# CORS - allow localhost frontends to call the service

CORS_ALLOWED_ORIGINS = [
    'https://talentbro.in',
    'https://www.talentbro.in',
    'https://ins.talentbro.in',
]
CORS_ALLOW_CREDENTIALS = True

# Origins allowed to make CSRF-protected (POST) calls from the SPA frontend.
CSRF_TRUSTED_ORIGINS = [
    'https://talentbro.in',
    'https://www.talentbro.in',
    'https://ins.talentbro.in',
]


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Sessions - keep authenticated users signed in for two weeks

SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # 14 days
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # survive browser restarts
SESSION_SAVE_EVERY_REQUEST = True  # sliding: extend the window on every visit


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Gemini — credentials sourced from C:\Anirban\Yaadly\Backend\.env
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '').strip()
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-2.5-flash-lite').strip()
# Dedicated Gemini 2.5 model for speech-to-text transcription (voice-mic in
# chat). Full 2.5 models accept audio input; also self-verifies the transcript.
GEMINI_STT_MODEL = os.environ.get('GEMINI_STT_MODEL', 'gemini-2.5-flash').strip()
# Dedicated model for mock interview conduction only.
GEMINI_MOCK_INTERVIEW_MODEL = os.environ.get(
    'GEMINI_MOCK_INTERVIEW_MODEL', 'gemini-3.1-flash-lite',
).strip()
# Dedicated model for the AI-powered student onboarding flow.
GEMINI_ONBOARDING_MODEL = os.environ.get(
    'GEMINI_ONBOARDING_MODEL', 'gemini-2.5-flash-lite',
).strip()

# Groq Whisper OCR — free-tier speech-to-text used for voice training
# transcription. If unset, the backend falls back to Gemini audio transcription.
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '').strip()
GROQ_MODEL = os.environ.get('GROQ_MODEL', 'whisper-large-v3-turbo').strip()
